### ISSUE TITLE
Using `SASS` in the `dooz` react project

### ISSUE THREAD

**Issue by maryamhdr** [bazimazi/dooz#6]
The project uses CSS modules for styling the elements. As you know SASS is just a CSS preprocessor that builds a CSS file at the end. SASS provides more functionality on top of CSS, which is exactly what we'll need to write reusable CSS code. We can start using SASS in React by installing the sass package via npm or yarn, updating our CSS files to `.scss` or `.sass`, and then updating our imports to use the new file extension.

**Comment by msynk** [comment]
nice 👌
